### GET all products
GET http://localhost:3001/api/products

### GET a product by Id
GET http://localhost:3001/api/products/682c9a8d6fd75cb7c058dbec

### POST a product
POST http://localhost:3001/api/products
Content-Type: application/json

{
  "name": "TEST PRODUCT",
  "sku": 1005,
  "stock": 1,
  "description": "TEST DESC",
  "price": 5.99,
  "category": "TEST CATEGORY",
  "supplier": "TEST SUPPLIER"
}

### PUT or UPDATE a product
PUT http://localhost:3001/api/products/682dfe696145d9360bd4fea0
Content-Type: application/json

{
  "name": "TEST PRODUCT 1",
  "sku": 1005,
  "stock": 0,
  "description": "TEST DESC",
  "price": 5.99,
  "category": "TEST CATEGORY",
  "supplier": "TEST SUPPLIER"
}
