### GET all sales
GET http://localhost:3001/api/sales


### GET a sale by Id
GET http://localhost:3001/api/sales/682c95006fd75cb7c058dbe7

### POST a sale
POST http://localhost:3001/api/sales
Content-Type: application/json

{
    "productId": "682d669c905734f88f56275e",
    "priceAtSale": 20,
    "quantity": 0,
    "totalAmount": 0,
    "cashierName": "Bernice",
    "paymentMethod": "paypal"
}

### PUT or UPDATE a sale
PUT http://localhost:3001/api/sales/682d6f17d56c436c8b9c174c
Content-Type: application/json

{   
    "productId": "682d669c905734f88f56275e",
    "priceAtSale": 12.99,
    "quantity": 5,
    "totalAmount": 64.95,
    "cashierName": "Bernice S. Sawal",
    "paymentMethod": "credit"
}

